version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  deploy:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run publish-win64
workflows:
    deploy:
      jobs:
        - deploy