version: 2.1
orbs:
  win: circleci/windows@2.4.0
  slack: circleci/slack@4.4.0
jobs:
  publish-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run publish-win
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run build-win
  publish-linux:
    docker:
      - image: cimg/base:edge
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - checkout
      - run: npm run publish-linux-circleci
  build-linux:
    docker:
      - image: cimg/base:edge
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - checkout
      - run: npm run build-linux-circleci
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  version: 2
  windows:
    jobs:
      - publish-windows:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-windows:
          filters:
            branches:
              only: master
  linux:
    jobs:
      - publish-linux:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-linux:
          filters:
            branches:
              only: master
