version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  publish-win64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run publish-win64
  publish-linux64:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: npm run publish-linux64
workflows:
    publish-win64:
      jobs:
        - publish-win64:
          type: approval
          filters:
            branches:
              only: circleci-project-setup
                
    publish-linux64:
      jobs:
        - publish-linux64:
          type: approval
          filters:
            branches:
              only: master
