version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  deploy:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: curl https://bootstrap.pypa.io/get-pip.py -O get-pip.py 
      - run: python ./get-pip.py
      - run: npm start publish-win64
workflows:
    deploy:
      jobs:
        - deploy