version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  deploy:
    executor:
      name: win/default   
    steps:
      - checkout
      - install-pip:
        steps:
          - run:
            command: curl https://bootstrap.pypa.io/get-pip.py -O get-pip.py 
            shell: powershell.exe
          - run: python ./get-pip.py
      - deploy-cleep-desktop:
        steps:
          - run: npm start publish-win64
workflows:
    deploy:
      jobs:
        - deploy