version: 2.1
orbs:
  win: circleci/windows@5.1.0
  slack: circleci/slack@5.1.1
jobs:
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: Installing node
          command: |
            choco install nvm
            nvm install 22
            nvm use 22
            node --version
      - checkout
      - run:
          name: Building
          command: npm run build-win
  publish-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: Installing node
          command: |
            choco install nvm
            nvm install 22
            nvm use 22
            node --version
      - checkout
      - run:
          name: Publishing
          command: npm run publish-win

  build-linux:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Installing node
          command: |
            curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
      - checkout
      - run:
          name: Building
          command: npm run build-linux
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  publish-linux:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Installing node
          command: |
            curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
      - checkout
      - run:
          name: Publishing
          command: npm run publish-linux

  build-macos:
    macos:
      xcode: 16.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - run:
          name: Installing node
          command: node --version
      - checkout
      - run:
          name: Building
          command: npm run build-macos
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  publish-macos:
    macos:
      xcode: 16.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - run:
          name: Installing node
          command: node --version
      - checkout
      - run:
          name: Publishing
          command: npm run publish-macos

workflows:
  version: 2
  windows:
    jobs:
      - publish-windows:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-windows:
          filters:
            branches:
              only: master
  linux:
    jobs:
      - publish-linux:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-linux:
          filters:
            branches:
              only: master
  macos:
    jobs:
      - publish-macos:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-macos:
          filters:
            branches:
              only: master
