version: 2.1
orbs:
  win: circleci/windows@2.4.0
  slack: circleci/slack@4.3.3
jobs:
  publish-windows64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run publish-win64
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  build-windows64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run build-win64
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  publish-linux64:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - checkout
      - run: npm run publish-linux64-circleci
  build-linux64:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - checkout
      - run: npm run build-linux64-circleci
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  version: 2
  windows64:
    jobs:
      - publish-windows64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-windows64:
          filters:
            branches:
              only: master
  linux64:
    jobs:
      - publish-linux64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-linux64:
          filters:
            branches:
              only: master
