version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  publish-win64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: npm run publish-win64
  publish-linux64:
    docker:
      image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run: npm run publish-linux64-circleci
workflows:
    publish-linux64:
      jobs:
        - publish-linux64:
          filters:
            branches:
              only: master
